WebApi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'rest_api/', include('rest_api.urls')),
    url(r'website/', include(('website.urls', 'website'), namespace='website')),
]

urlpatterns += staticfiles_urlpatterns()

rest_api/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('departments/', views.DepartmentsNewList.as_view()),
    path('departments/<int:pk>', views.DepartmentsNewList.as_view()),
    path('employees/', views.EmployeesNewList.as_view()),
    path('employees/<int:pk>', views.EmployeesNewList.as_view()),
]

website/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('index/', views.index, name='index'),
    path('create_department/', views.create_department, name='create_department'),
    path('delete_department/', views.delete_department, name='delete_department'),
    path('delete_employee/', views.delete_employee, name='delete_employee'),
]

rest_api/models.py
from django.db import models


class DeptNew(models.Model):
    # department_id = models.IntegerField()
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return '__all__'


class EmpNew(models.Model):
    # emp_id = models.CharField(max_length=5, primary_key=True)
    name = models.CharField(max_length=200, unique=True)
    department_id = models.ForeignKey(DeptNew, on_delete=models.CASCADE)
    dob = models.DateField()

    def __str__(self):
        return '__all__'

website/models.py
from django.db import models

# Create your models here.

rest_api/views.py
from rest_framework.views import APIView
from .models import EmpNew
from .models import DeptNew
from .serializer import DepartmentsSerializer
from .serializer import EmployeesSerializer
from django.http import Http404
from rest_framework.response import Response
from rest_framework import status


class DepartmentsNewList(APIView):

    def get_object(self, pk):
        try:
            return DeptNew.objects.get(pk=pk)
        except DeptNew.DoesNotExist:
            raise Http404

    def get(self, request):
        name = request.GET.get("name")
        if name is not None:
            dep = DeptNew.objects.get(name=name)
            ser = DepartmentsSerializer(dep)
        else:
            # emp = EmployeesNew.objects.all()
            dep = DeptNew.objects.all()
            ser = DepartmentsSerializer(dep, many=True)
        return Response(ser.data)

    def post(self, request):
        serializer = DepartmentsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, pk, format=None):
        dept = self.get_object(pk)

        serializer = DepartmentsSerializer(dept, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        dept = self.get_object(pk)
        dept.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class EmployeesNewList(APIView):

    def get_object(self, pk):
        try:
            return EmpNew.objects.get(pk=pk)
        except EmpNew.DoesNotExist:
            raise Http404

    def get(self, request):
        # emp = EmployeesNew.objects.all()

        name = request.GET.get("name")
        if name is not None:
            emp = EmpNew.objects.get(name=name)
            ser = EmployeesSerializer(emp)
        else:
            # emp = EmployeesNew.objects.all()
            emp = EmpNew.objects.all()
            ser = EmployeesSerializer(emp, many=True)
        return Response(ser.data)

    def post(self, request):
        serializer = EmployeesSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, pk, format=None):
        emp = self.get_object(pk)
        serializer = EmployeesSerializer(emp, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        emp = self.get_object(pk)
        emp.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


website/views.py
from django.shortcuts import HttpResponse, render_to_response
import requests
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseRedirect
from django.conf import settings


@csrf_exempt
def index(request):
    if request.method == 'POST':
        if request.POST.get('type') == 'department':
            create_department(request)
        elif request.POST.get('type') == 'department_edit':
            edit_department(request)
        elif request.POST.get('type') == 'employee_edit':
            edit_employee(request)
        elif request.POST.get('type') == 'employee':
            create_employee(request)
        return HttpResponseRedirect(request.path_info)

    emp = get_employees()
    dep = get_departments()

    return render_to_response("website/index.html", {'employees': emp, 'departments': dep})


def edit_department(request):
    _rest_url = settings.REST_URL
    dep = get_dept_by_name(request.POST.get("dept_name"))
    url = f"{_rest_url}/departments/{dep['id']}?format=json"
    params = {"name": request.POST.get("dept_name"), "description": request.POST.get("dept_description"), "id": dep['id']}

    r = requests.put(url, params)
    return HttpResponse(status=201)


def create_department(request):
    _rest_url = settings.REST_URL
    url = f'{_rest_url}/departments/?format=json'
    params = {"name": request.POST.get("dept_name"), "description": request.POST.get("dept_description")}
    r = requests.post(url, json=params)
    return HttpResponse(status=201)


@csrf_exempt
def delete_department(request):
    _rest_url = settings.REST_URL
    dep_id = request.POST.get('dept_id')
    url = f'{_rest_url}/departments/{dep_id}?format=json'
    requests.delete(url)
    return JsonResponse({"status":"Success"})

@csrf_exempt
def delete_employee(request):
    _rest_url = settings.REST_URL
    emp_id = request.POST.get('emp_id')
    url = f'{_rest_url}/employees/{emp_id}?format=json'
    requests.delete(url)
    return JsonResponse({"status": "Success"})


def edit_employee(request):
    _rest_url = settings.REST_URL
    emp = get_emp_by_name(request.POST.get("emp_name"))
    dep = get_dept_by_name(request.POST.get("emp_dept_name"))
    url = f"{_rest_url}/employees/{emp['id']}?format=json"
    params = {"name": request.POST.get("emp_name"), "dob": request.POST.get("emp_dob"),
              "id": emp['id'], "department_id": dep["id"]}

    r = requests.put(url, params)

    return HttpResponse(status=201)


def create_employee(request):
    _rest_url = settings.REST_URL
    url = f'{_rest_url}/employees/?format=json'

    dept = get_dept_by_name(request.POST.get("emp_dept_name"))

    params = {"name": request.POST.get("emp_name"), "dob": request.POST.get("emp_dob"), "department_id": dept["id"]}
    r = requests.post(url, json=params)
    return HttpResponse(status=201)


def get_dept_by_name(name):
    _rest_url = settings.REST_URL
    url = f'{_rest_url}/departments/?format=json&name={name}'
    r = requests.get(url)
    return r.json()


def get_emp_by_name(name):
    _rest_url = settings.REST_URL
    url = f'{_rest_url}/employees/?format=json&name={name}'
    r = requests.get(url)
    return r.json()


def get_departments():
    _rest_url = settings.REST_URL
    url = f'{_rest_url}/departments/?format=json'
    params = None
    r = requests.get(url, params=params)
    return r.json()


def get_employees():
    _rest_url = settings.REST_URL
    url = f'{_rest_url}/employees/?format=json'
    params = None
    r = requests.get(url, params=params)
    return r.json()


website/templates/website/index.html
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="tab">
      <button class="tablinks" onclick="openTab(event, 'Department')">Departments</button>
      <button class="tablinks" onclick="openTab(event, 'Employee')">Employees</button>
    </div>

    <div id="Department" class="tabcontent">
        <h3>Departments</h3>
        <input type="button" value="Create new department" onclick="create_dept();" style="float: right;">
        <br>
        <br>
        <table class="custom_table" id="dept_table">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th></th>
            </tr>
            {% for dep in departments %}
                <tr>
                    {% for key, value in dep.items %}
                        {% if key == "id" %}
                            <input type="hidden" name="dept_id" id="dept_id" value="{{ value }}">
                        {% else %}
                            <td id="dept_{{key}}">{{ value }}</td>
                        {% endif %}
                    {% endfor%}
                    <td><a href="#" class="editDept">Edit</a></td>
                    <td><a href="#" class="deleteDept">Delete</a></td>
                </tr>
            {% endfor %}
        </table>
        <form action="{% url 'website:index' %}" method="POST" id="dept_form">
            {% csrf_token %}
            <label>Name</label><br>
            <input type="text" name="dept_name" id="dept_name"><br>
            <label>Description</label><br>
            <input type="text" name="dept_description"><br>
            <input type="hidden" name="type" id="dept_hide" value="department">
            <input onclick="dept_form_cancel();" type="cancel" value="Cancel" />
            <input type="submit" value="Submit" />
        </form>
    </div>

    <div id="Employee" class="tabcontent">
      <h3>Employees</h3>
        <input type="button" value="Create new Employee" onclick="create_emp();" style="float: right;">
        <br>
        <br>
      <table class="custom_table" id="emp_table">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Department</th>
            <th></th>
            <th></th>
        </tr>
        {% for emp in employees %}
            <tr>
                {% for key, value in emp.items %}
                    {% if key == "id" or key == "dob" or key == "department_id" %}
                        <input type="hidden" name="emp_{{key}}" id="emp_h_{{key}}" value="{{ value }}">
                    {% else %}
                        <td id="emp_{{key}}">{{ value }}</td>
                    {% endif %}
                {% endfor%}
                <td><a href="#" class="editEmp">Edit</a></td>
                <td><a href="#" class="deleteEmp">Delete</a></td>
            </tr>
        {% endfor %}
      </table>
        <form action="{% url 'website:index' %}" method="POST" id="emp_form">
            {% csrf_token %}
            <label>Name</label><br>
            <input type="text" name="emp_name"><br>
            <label>Date of Birth</label><br>
            <input type="date" name="emp_dob"><br>
            <label>Department</label><br>
            <select name="emp_dept_name">
                {% for dep in departments %}
                    {% for key, value in dep.items %}
                        {% if key == "name" %}
                            <option value="{{ value }}">{{ value }}</option>
                        {% endif %}
                    {% endfor%}
                {% endfor %}
            </select><br>
            <input type="hidden" name="type" id="emp_hide" value="employee">
            <input onclick="emp_form_cancel();" type="cancel" value="Cancel" />
            <input id="submit" type="submit" value="Submit" />
        </form>
    </div>

</body>

<style>
.custom_table {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

.custom_table td, .custom_table th {
  border: 1px solid #ddd;
  padding: 8px;
}

.custom_table tr:nth-child(even){background-color: #f2f2f2;}

.custom_table tr:hover {background-color: #ddd;}

.custom_table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: lightseagreen;
  color: white;
}

body {font-family: Arial;}

/* Style the tab */
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
  font-size: 17px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}

input[type=text], input[type=date], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit], input[type=cancel]{
  width: 25%;
  background-color: lightseagreen;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover, input[type=cancel]:hover{
  background-color: darkseagreen;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

</style>

<script>



function openTab(evt, tabname) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabname).style.display = "block";
  evt.currentTarget.className += " active";
}

function create_dept(){
    $("#dept_table").hide();
    $("#dept_form").show();
    $("#dept_hide").val("department");
    $("#dept_form").trigger("reset");
}

function create_emp(){
    $("#emp_table").hide();
    $("#emp_form").show();
    $("#emp_hide").val("employee");
    $("#emp_form").trigger("reset");
}

$(function(){
    $(".editDept").click(function(){
        var dept_name = $(this).parent().siblings("#dept_name").text();
        var dept_description = $(this).parent().siblings("#dept_description").text();
        $("[name='dept_name']").val(dept_name);
        $("[name='dept_description']").val(dept_description);
        $("#dept_hide").val("department_edit");
        $("#dept_table").hide();
        $("#dept_form").show();
    });

});

$(function(){
    $(".editEmp").click(function(){
        var emp_name = $(this).parent().siblings("#emp_name").text();
        var emp_age = $(this).parent().siblings("#emp_h_dob").val();
        var emp_dept_name = $(this).parent().siblings("#emp_dept_name").text();
        $("[name='emp_name']").val(emp_name);
        $("[name='emp_dob']").val(emp_age);
        $("[name='emp_dept_name'] option[value=" + emp_dept_name + "]").attr('selected','selected');
        $("#emp_hide").val("employee_edit");
        $("#emp_table").hide();
        $("#emp_form").show();
    });

});

$(function(){
    $(".deleteDept").click(function(){

        var dept_id = $(this).parent().siblings("#dept_id").val();
        $("#dept_hide").val("");

        $.ajax({
            url: '/website/delete_department/',
            type: 'POST',
            data: {
              'dept_id': dept_id,
              'type': 'department_delete'
            },
            dataType: 'json',
            success: function (data) {
              $("#dept_hide").val("department");
              window.location.reload(false);
            }
          });

    });
    return false;

});

$(function(){
    $(".deleteEmp").click(function(){

        var emp_id = $(this).parent().siblings("#emp_h_id").val();
        $("#emp_hide").val("");

        $.ajax({
            url: '/website/delete_employee/',
            type: 'POST',
            data: {
              'emp_id': emp_id,
              'type': 'employee_delete'
            },
            dataType: 'json',
            success: function (data) {
              $("#emp_hide").val("employee");
              window.location.reload(false);
            }
          });

    });
});

function dept_form_cancel(){
    $("#dept_form").trigger("reset");
    $("#dept_form").hide();
    $("#dept_table").show();
    $("#dept_hide").val("department");
}

function emp_form_cancel(){
    $("#emp_form").trigger("reset");
    $("#emp_form").hide();
    $("#emp_table").show();
    $("#emp_hide").val("employee");
}

$( document ).ready(function() {
    $("#dept_form").hide();
    $("#emp_form").hide();
    $("#dept_hide").val("department");
    $("#emp_hide").val("employee");
    $("#dept_form").trigger("reset");
    $("#emp_form").trigger("reset");
});
</script>